#!/usr/bin/env python

"""
Topic:
Desc:
"""

from datetime import datetime, timedela

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 
            'Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date=None):

    if start_date is None :
        start_date = datetiem.today()

    day_num = start_date.weekday()

    day_name_target = weekdays.index(dayname)

    days_ago = (7 + day_num -day_num_target) % 7

    if days_ago == 0:
        days_ago = 7

    target_date = start_date - timedelta(days=days_ago)

    return target_date


